services:
  # Базы данных для каждого сервиса
  postgres-session:
    image: dockerhub.timeweb.cloud/library/postgres:15
    environment:
      POSTGRES_DB: sessiondb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-session-data:/var/lib/postgresql/data

  postgres-order:
    image: dockerhub.timeweb.cloud/library/postgres:15
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

  postgres-payout:
    image: dockerhub.timeweb.cloud/library/postgres:15
    environment:
      POSTGRES_DB: payoutdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - postgres-payout-data:/var/lib/postgresql/data

  # Redis для кэша и идемпотентности
  redis:
    image: dockerhub.timeweb.cloud/library/redis:7-alpine
    ports:
      - "6379:6379"

  # Kafka и Zookeeper
  zookeeper:
    image: dockerhub.timeweb.cloud/confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: dockerhub.timeweb.cloud/confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9999:9999"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9999
      KAFKA_JMX_HOSTNAME: kafka
      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote=true
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Dcom.sun.management.jmxremote.rmi.port=9999
        -Djava.rmi.server.hostname=kafka

      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 1

      KAFKA_SOCKET_REQUEST_MAX_BYTES: 209715200
      KAFKA_MESSAGE_MAX_BYTES: 209715200
      KAFKA_REPLICA_FETCH_MAX_BYTES: 209715200
      KAFKA_CONNECTIONS_MAX_IDLE_MS: 600000
      KAFKA_NETWORK_REQUEST_TIMEOUT_MS: 30000

    healthcheck:
      test: [ "CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Kafka Exporter для сбора JMX метрик
  kafka-exporter:
    image: dockerhub.timeweb.cloud/bitnami/jmx-exporter:latest
    ports:
      - "8080:8080"
    volumes:
      # Монтируем ваш локальный файл конфигурации
      - ./jmx-exporter-config.yml:/opt/bitnami/jmx-exporter/config.yml
    environment:
      # Переменная окружения, которая указывает на config (опционально, но помогает)
      - JMX_EXPORTER_CONFIG=/opt/bitnami/jmx-exporter/config.yml
    command:
      # Передаём параметры в правильном порядке: <порт> <путь к конфигу>
      - "8080"
      - "/opt/bitnami/jmx-exporter/config.yml"

  prometheus:
    image: dockerhub.timeweb.cloud/prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: dockerhub.timeweb.cloud/grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      # Дашборды JSON в отдельную папку
      - ./grafana-dashboards:/var/lib/grafana/dashboards
      # Конфиги провижининга в стандартную папку
      - ./grafana/provisioning:/etc/grafana/provisioning
      # Данные
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/spring-boot-3x-stats.json
      - GF_INSTALL_PLUGINS=
      - GF_LOG_LEVEL=info
      - GF_LOG_MODE=console
    restart: unless-stopped
    networks:
      - delivery-microservices_default
    depends_on:
      - prometheus

  elasticsearch:
    image: dockerhub.timeweb.cloud/elastic/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  logstash:
    image: dockerhub.timeweb.cloud/elastic/logstash:7.10.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"

  kibana:
    image: dockerhub.timeweb.cloud/elastic/kibana:7.10.2
    ports:
      - "5601:5601"

  jaeger:
    image: dockerhub.timeweb.cloud/jaegertracing/all-in-one:1.47
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  # Микросервисы
  session-service:
    build: ./session-service
    depends_on:
      - postgres-session
      - redis
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-session:5432/sessiondb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SERVER_PORT: 8081

  order-service:
    build: ./order-service
    depends_on:
      - postgres-order
      - redis
      - kafka
      - session-service
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-order:5432/orderdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SESSION_SERVICE_URL: http://session-service:8081
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SERVER_PORT: 8082

  payout-service:
    build: ./payout-service
    depends_on:
      - postgres-payout
      - kafka
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-payout:5432/payoutdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SERVER_PORT: 8083

volumes:
  postgres-session-data:
  postgres-order-data:
  postgres-payout-data:
  grafana-data:
    driver: local

networks:
  delivery-microservices_default:
    driver: bridge

