{
 "title": "JVM",
 "description": "Dashboard for Micrometer instrumented applications (Java, Spring Boot, Micronaut)",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(job)" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_memory_used_bytes{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Facts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"$job\", instance=~\"$instance\"}*1000"
    }
   ]
  },
  {
   "title": "Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$job\", instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$job\", instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "HTTP Rate"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\", status=~\"5..\"}[1m]))",
     "legendFormat": "HTTP - 5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{job=\"$job\", instance=~\"$instance\", status!~\"5..\"}[1m]))/sum(rate(http_server_requests_seconds_count{job=\"$job\", instance=~\"$instance\", status!~\"5..\"}[1m]))",
     "legendFormat": "HTTP - AVG"
    },
    {
     "expr": "max(http_server_requests_seconds_max{job=\"$job\", instance=~\"$instance\", status!~\"5..\"})",
     "legendFormat": "HTTP - MAX"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Live Threads"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Daemon Threads"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Peak Threads"
    }
   ]
  },
  { "title": "JVM Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "JVM Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=~\"$instance\", area=\"heap\"}) by (job)",
     "legendFormat": "used - {{job}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", instance=~\"$instance\", area=\"heap\"}) by (job)",
     "legendFormat": "committed - {{job}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", instance=~\"$instance\", area=\"heap\"}) by (job)",
     "legendFormat": "max - {{job}}"
    }
   ]
  },
  {
   "title": "JVM Non-Heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=~\"$instance\", area=\"nonheap\"}) by (job)",
     "legendFormat": "used - {{job}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", instance=~\"$instance\", area=\"nonheap\"}) by (job)",
     "legendFormat": "committed - {{job}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", instance=~\"$instance\", area=\"nonheap\"}) by (job)",
     "legendFormat": "max - {{job}}"
    }
   ]
  },
  {
   "title": "JVM Total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", instance=~\"$instance\"}) by (job)",
     "legendFormat": "used - {{job}}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", instance=~\"$instance\"}) by (job)",
     "legendFormat": "committed - {{job}}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{job=\"$job\", instance=~\"$instance\"}) by (job)",
     "legendFormat": "max - {{job}}"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_files_open_files{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "open - {{job}}"
    },
    {
     "expr": "process_files_max_files{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "max - {{job}}"
    }
   ]
  },
  { "title": "JVM Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "system - {{job}}"
    },
    {
     "expr": "process_cpu_usage{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "process - {{job}}"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "live - {{job}}"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "daemon - {{job}}"
    },
    {
     "expr": "jvm_threads_peak_threads{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "peak - {{job}}"
    }
   ]
  },
  {
   "title": "Classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"$job\", instance=~\"$instance\"}",
     "legendFormat": "loaded - {{job}}"
    }
   ]
  },
  {
   "title": "Class delta",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "delta(jvm_classes_loaded_classes{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "delta-1m - {{job}}"
    }
   ]
  },
  { "title": "Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_count{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "{{job}} - {{cause}}"
    }
   ]
  },
  {
   "title": "Avg GC Pause Durations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_pause_seconds_sum{job=\"$job\", instance=~\"$instance\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "avg - {{job}} - {{cause}}"
    }
   ]
  },
  {
   "title": "Allocated/Promoted",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "allocated - {{job}}"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=\"$job\", instance=~\"$instance\"}[1m])",
     "legendFormat": "promoted - {{job}}"
    }
   ]
  }
 ]
}