{
 "title": "Kafka",
 "description": "Kafka resource usage and throughput",
 "tags": [ "Kafka" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(kafka_server_brokertopicmetrics_messagesin_total{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Message In Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_server_brokertopicmetrics_messagesin_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "Messages In"
    }
   ]
  },
  {
   "title": "Leader Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_leadercount{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Leader Count"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Partition Count"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underminisrpartitioncount{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Under Replicated"
    }
   ]
  },
  {
   "title": "At Min ISR Partitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_atminisrpartitioncount{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "At Min ISR"
    }
   ]
  },
  {
   "title": "Delayed Operation Purgatory Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (kafka_server_delayedoperationpurgatory_purgatorysize{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Delayed Operations Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (kafka_server_delayedoperationpurgatory_numdelayedoperations{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Broker State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_brokerstate{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Broker State"
    }
   ]
  },
  {
   "title": "Yammer Metrics Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkaserver_yammer_metrics_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Metrics Count"
    }
   ]
  },
  {
   "title": "Incremental Fetch Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(name) (kafka_server_fetchsessioncache_numincrementalfetchsessions{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Fetch Sessions"
    }
   ]
  }
 ]
}