{
 "title": "PostgreSQL",
 "description": "Database connection metrics via HikariCP",
 "tags": [
  "postgres",
  "db",
  "hikaricp"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(hikaricp_connections, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(hikaricp_connections{job=~\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Database Connection Pool Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Pools",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(hikaricp_connections{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "Active Pools"
    }
   ]
  },
  {
   "title": "Max Pool Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_max{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_active{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_idle{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Pending Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_pending{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_timeout_total{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Avg Timeout",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(hikaricp_connection_timeout_total{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Min Pool Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(hikaricp_connections_min{job=~\"$job\", instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Connection Pool Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_active{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_idle{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Pending Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_pending{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Avg Connection Creation Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_creation_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(hikaricp_connections_creation_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Avg Connection Acquire Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_acquire_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(hikaricp_connections_acquire_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Avg Connection Usage Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_usage_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(hikaricp_connections_usage_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Pool Size Limits",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hikaricp_connections_max{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "max - {{job}}"
    },
    {
     "expr": "hikaricp_connections_min{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "min - {{job}}"
    }
   ]
  },
  {
   "title": "Connection Timeouts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(hikaricp_connections_timeout_total{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}} - {{instance}}"
    }
   ]
  }
 ]
}